### ISSUE TITLE
TransactionBuilder class have a bug, the method may be should chanag to  Utils.reverseBytes(txn.getTransactionIdBytes() 

### ISSUE THREAD

**Issue by metanet4jDev** [twostack/bitcoin4j#12]
public TransactionBuilder spendFromTransaction(Transaction txn, int outputIndex, long sequenceNumber, UnlockingScriptBuilder unlocker) {
        TransactionInput input = new TransactionInput(Utils.reverseBytes(txn.getTransactionIdBytes()), (long)outputIndex, sequenceNumber, unlocker);
        this.spendingMap.put(txn.getTransactionId(), ((TransactionOutput)txn.getOutputs().get(outputIndex)).getAmount());
        this.inputs.add(input);
        return this;
    }

**Comment by stephanfeb** [comment]
Latest code push fixes this. Thanks for reporting !
